// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRdbcQlQq4sxqTlb2v-Dl5h0JyRCzxsp8',
    appId: '1:438732190711:web:0de959ee6a5832976a34f2',
    messagingSenderId: '438732190711',
    projectId: 'reddit-clone-tutorial-ffd78',
    authDomain: 'reddit-clone-tutorial-ffd78.firebaseapp.com',
    storageBucket: 'reddit-clone-tutorial-ffd78.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATQPFAl2FiF5zxJF8DN59z5wEKazUmPio',
    appId: '1:438732190711:android:8a8c347f3d4c58606a34f2',
    messagingSenderId: '438732190711',
    projectId: 'reddit-clone-tutorial-ffd78',
    storageBucket: 'reddit-clone-tutorial-ffd78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgLnJIhxYR2lwm_kDqlYcdbB0xjSc5q4M',
    appId: '1:438732190711:ios:d70c79ee204a27c56a34f2',
    messagingSenderId: '438732190711',
    projectId: 'reddit-clone-tutorial-ffd78',
    storageBucket: 'reddit-clone-tutorial-ffd78.appspot.com',
    iosBundleId: 'com.example.redditCloneNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgLnJIhxYR2lwm_kDqlYcdbB0xjSc5q4M',
    appId: '1:438732190711:ios:d70c79ee204a27c56a34f2',
    messagingSenderId: '438732190711',
    projectId: 'reddit-clone-tutorial-ffd78',
    storageBucket: 'reddit-clone-tutorial-ffd78.appspot.com',
    iosBundleId: 'com.example.redditCloneNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRdbcQlQq4sxqTlb2v-Dl5h0JyRCzxsp8',
    appId: '1:438732190711:web:bc43677514e78d856a34f2',
    messagingSenderId: '438732190711',
    projectId: 'reddit-clone-tutorial-ffd78',
    authDomain: 'reddit-clone-tutorial-ffd78.firebaseapp.com',
    storageBucket: 'reddit-clone-tutorial-ffd78.appspot.com',
  );
}
